[modules]
log_file
radius
sstp
auth_mschap_v2
auth_mschap_v1
auth_chap_md5
auth_pap
ippool

[core]
log-error=/var/log/accel-ppp/core.log
thread-count=4

[common]
single-session=replace
sid-case=upper
sid-source=urandom

[ppp]
verbose=1
min-mtu=1280
mtu=1400
mru=1400
ipv4=require
ipv6=deny
lcp-echo-interval=20
lcp-echo-failure=3
lcp-echo-timeout=120
unit-cache=16

[auth]
timeout=5
max-failure=3

[sstp]
bind=0.0.0.0
port=4406
verbose=1
accept=ssl
ssl-protocol=tls1.2,tls1.3
ssl-pemfile=/etc/accel-ppp/server.crt
ssl-keyfile=/etc/accel-ppp/server.key
timeout=30
hello-interval=30
ip-pool=sstp
ifname=sstp%d

[radius]
dictionary=/usr/share/accel-ppp/radius/dictionary
nas-identifier=sstp-@DOMAIN@
nas-ip-address=127.0.0.1
gw-ip-address=10.101.0.1
server=127.0.0.1,@RADIUS_SECRET@,auth-port=1812,acct-port=1813,req-limit=50,fail-timeout=5,max-fail=3,weight=1
dae-server=127.0.0.1:3799,@RADIUS_SECRET@
dae-allowed=127.0.0.1
verbose=1
interim-verbose=0
timeout=3
max-try=3
strip-realm=1
acct-interim-interval=20
nas-port-id-in-req=1
blast-protection=1

[client-ip-range]
0.0.0.0/0

[ip-pool]
gw-ip-address=10.101.0.1
10.101.0.10-10.101.0.250,name=sstp

[log]
log-file=/var/log/accel-ppp/accel-ppp.log
log-emerg=/var/log/accel-ppp/emerg.log
log-fail-file=/var/log/accel-ppp/auth-fail.log
copy=1
level=4
per-session=1
per-session-dir=/var/log/accel-ppp/sessions

[cli]
verbose=1
tcp=127.0.0.1:2001
sessions-columns=ifname,username,ip,type,state,uptime,calling-sid,sid,rx-bytes,tx-bytes
