<?php
declare(strict_types=1);
final class DirectStockAdjustmentService {
 public function __construct(private PDO $db,private AuthorizationContext $auth){}
 public function create(array $input):array{
  if(!in_array($this->auth->role(),['system_owner','superadmin','network_manager','admin','accountant','finance'],true))throw new DomainException('FORBIDDEN');
  $this->auth->assertCan(['stock_inventory','card_warehouses','warehouse_stock_transfer']);$net=$this->auth->activeNetworkId();if($net<=0||!$this->auth->canAccessNetwork($net)||isset($input['network_id'])&&(int)$input['network_id']!==$net)throw new DomainException('FORBIDDEN_NETWORK');
  $warehouse=(int)($input['warehouse_admin_id']??$input['admin_id']??0);$this->auth->assertCanAccessAdmin($warehouse);
  if(isset($input['adjustment_type'])&&!is_string($input['adjustment_type']))throw new InvalidArgumentException('INVALID_ADJUSTMENT_TYPE');$type=$input['adjustment_type']??'damaged';$type=['damage_loss'=>'damaged','surplus_found'=>'surplus'][$type]??$type;if($type==='surplus')throw new DomainException('SURPLUS_REQUIRES_CARD_IMPORT');if(!in_array($type,['damaged','lost','deficit'],true))throw new InvalidArgumentException('INVALID_ADJUSTMENT_TYPE');
  $reason=$input['reason']??'';$key=$input['request_key']??'';if(!is_string($reason)||trim($reason)===''||mb_strlen($reason)>1000)throw new InvalidArgumentException('INVALID_REASON');if(!is_string($key)||!preg_match('/^[A-Za-z0-9_.:-]{8,100}$/',$key))throw new InvalidArgumentException('REQUEST_KEY_REQUIRED');
  $items=$input['items']??[];if(!is_array($items)||!array_is_list($items)||count($items)!==1||!is_array($items[0]))throw new InvalidArgumentException('ONE_PROFILE_PER_REQUEST');$item=$items[0];$profile=$item['profile_name']??'';if(!is_string($profile)||trim($profile)===''||mb_strlen($profile)>64)throw new InvalidArgumentException('INVALID_PROFILE');$profile=trim($profile);
  $requested=$item['sheet_numbers']??'';$count=$item['sheets_count']??1;if(!is_int($count)||$count<1||$count>500)throw new InvalidArgumentException('INVALID_SHEET_COUNT');$sheets=[];
  if(is_array($requested)){foreach($requested as $number){if(!is_int($number)||$number<1)throw new InvalidArgumentException('INVALID_SHEETS');$sheets[]=$number;}}
  elseif(is_string($requested)){if(strlen($requested)>6000)throw new InvalidArgumentException('INVALID_SHEETS');$requested=preg_replace('/\s+/u','',$requested);if($requested!==''){foreach(explode(',',$requested) as $piece){if(!preg_match('/^(\d{1,9})(?:-(\d{1,9}))?$/',$piece,$m)||(int)$m[1]<1)throw new InvalidArgumentException('INVALID_SHEETS');$first=(int)$m[1];$last=(int)($m[2]??$m[1]);if($last<$first||$last-$first>499)throw new InvalidArgumentException('INVALID_SHEETS');for($n=$first;$n<=$last;$n++)$sheets[]=$n;if(count($sheets)>500)throw new InvalidArgumentException('INVALID_SHEETS');}}}
  else throw new InvalidArgumentException('INVALID_SHEETS');$sheets=array_values(array_unique($sheets));sort($sheets);if(count($sheets)>500)throw new InvalidArgumentException('INVALID_SHEETS');
  $fingerprint=hash('sha256',json_encode([$warehouse,$profile,$type,trim($reason),$sheets,$count],JSON_THROW_ON_ERROR));$this->db->beginTransaction();
  try{
   $locks=array_unique([$warehouse,$this->auth->id()]);sort($locks);foreach($locks as $lock){$q=$this->db->prepare('SELECT id FROM um_admins WHERE id=? FOR UPDATE');$q->execute([$lock]);if(!$q->fetchColumn())throw new DomainException('FORBIDDEN_NETWORK');}
   $q=$this->db->prepare('SELECT id,status,direct_request_hash FROM um_stock_inventories WHERE network_id=? AND created_by=? AND direct_request_key=? FOR UPDATE');$q->execute([$net,$this->auth->id(),$key]);if($old=$q->fetch(PDO::FETCH_ASSOC)){if(!hash_equals((string)$old['direct_request_hash'],$fingerprint))throw new DomainException('IDEMPOTENCY_CONFLICT');if($old['status']!=='completed')throw new DomainException('INVENTORY_LOCKED');$this->db->commit();return ['success'=>true,'inventory_id'=>(int)$old['id'],'replayed'=>true,'message'=>'التسوية سبق ترحيلها دون تكرار الأثر'];}
   $safe="network_id=? AND owner_admin_id=? AND profile_name=? AND is_sold=0 AND invoice_id IS NULL AND first_login IS NULL AND (status IS NULL OR status IN ('active','disabled')) AND username NOT LIKE 'router\\_%' AND COALESCE(comment,'') NOT LIKE 'استيراد محجور من User Manager%' AND NOT EXISTS(SELECT 1 FROM radacct r WHERE r.network_id=um_vouchers_meta.network_id AND r.username=um_vouchers_meta.username)";$params=[$net,$warehouse,$profile];
   $q=$this->db->prepare('SELECT COUNT(*) cards,COUNT(DISTINCT sheet_no) sheets,ROUND(AVG(purchase_cost),2) cost,MAX(price) retail FROM um_vouchers_meta WHERE '.$safe.' FOR UPDATE');$q->execute($params);$book=$q->fetch(PDO::FETCH_ASSOC);if(!(int)$book['cards'])throw new DomainException('INSUFFICIENT_STOCK');
   if(!$sheets){$q=$this->db->prepare('SELECT DISTINCT sheet_no FROM um_vouchers_meta WHERE '.$safe.' AND sheet_no>0 ORDER BY sheet_no LIMIT '.$count.' FOR UPDATE');$q->execute($params);$sheets=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));if(count($sheets)!==$count)throw new DomainException('INSUFFICIENT_STOCK');}
   $marks=implode(',',array_fill(0,count($sheets),'?'));$q=$this->db->prepare('SELECT id,sheet_no FROM um_vouchers_meta WHERE '.$safe." AND sheet_no IN ($marks) ORDER BY id LIMIT 5001 FOR UPDATE");$q->execute(array_merge($params,$sheets));$cards=$q->fetchAll(PDO::FETCH_ASSOC);if(count($cards)>5000)throw new DomainException('POSTING_BATCH_REQUIRED');if(count(array_unique(array_column($cards,'sheet_no')))!==count($sheets))throw new DomainException('INSUFFICIENT_STOCK');
   $number='INV-DIRECT-'.bin2hex(random_bytes(16));$q=$this->db->prepare("INSERT INTO um_stock_inventories(inventory_no,network_id,warehouse_admin_id,inventory_date,status,notes,created_by,total_book_cards,total_actual_cards,direct_request_key,direct_request_hash) VALUES(?,?,?,CURDATE(),'in_progress',?,?,?,?,?,?)");$actual=(int)$book['cards']-count($cards);$q->execute([$number,$net,$warehouse,trim($reason),$this->auth->id(),$book['cards'],$actual,$key,$fingerprint]);$id=(int)$this->db->lastInsertId();
   $q=$this->db->prepare('INSERT INTO um_stock_inventory_lines(inventory_id,profile_name,book_sheets_count,book_cards_count,actual_sheets_count,actual_cards_count,cost_price,retail_price,variance_cards) VALUES(?,?,?,?,?,?,?,?,?)');$q->execute([$id,$profile,$book['sheets'],$book['cards'],max(0,(int)$book['sheets']-count($sheets)),$actual,$book['cost'],$book['retail'],-count($cards)]);
   require_once __DIR__.'/StockInventoryPostingService.php';$result=(new StockInventoryPostingService($this->db,$this->auth))->post($id,['selected_card_ids'=>[$profile=>array_map('intval',array_column($cards,'id'))],'adjustment_type'=>$type,'reason'=>trim($reason)]);$this->db->commit();return $result+['inventory_id'=>$id,'adjustment_type'=>$type];
  }catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
}
