<?php
declare(strict_types=1);
final class InstantBalanceTransferService {
 public function __construct(private PDO $db,private AuthorizationContext $auth){}
 private function cents(string $s):int{if(!preg_match('/^(\d{1,12})(?:\.(\d{1,2}))?$/',$s,$m))throw new InvalidArgumentException('INVALID_AMOUNT');return (int)$m[1]*100+(int)str_pad($m[2]??'',2,'0');}
 private function money(int $n):string{return intdiv($n,100).'.'.str_pad((string)($n%100),2,'0',STR_PAD_LEFT);}
 public function transfer(array $input):array{
  $this->auth->assertCan(['instant_balance_transfer','instant_balance']);$net=$this->auth->activeNetworkId();if($net<=0||!$this->auth->canAccessNetwork($net)||isset($input['network_id'])&&(int)$input['network_id']!==$net)throw new DomainException('FORBIDDEN_NETWORK');
  $target=$input['receiver_admin_id']??null;if((!is_int($target)&&!is_string($target))||!preg_match('/^[1-9][0-9]{0,9}$/',(string)$target))throw new InvalidArgumentException('INVALID_RECEIVER');$target=(int)$target;$source=$this->auth->id();if($source===$target)throw new InvalidArgumentException('SAME_ACCOUNT');
  $amount=$input['amount']??null;if(!is_string($amount)&&!is_int($amount))throw new InvalidArgumentException('INVALID_AMOUNT');$amount=$this->cents((string)$amount);if($amount<=0)throw new InvalidArgumentException('INVALID_AMOUNT');
  $key=$input['request_key']??'';$notes=$input['notes']??'';if(!is_string($key)||!preg_match('/^[A-Za-z0-9_.:-]{8,100}$/',$key))throw new InvalidArgumentException('REQUEST_KEY_REQUIRED');if(!is_string($notes)||mb_strlen($notes)>255)throw new InvalidArgumentException('INVALID_NOTES');if(!empty($input['expires_at']))throw new InvalidArgumentException('EXPIRY_FROM_SOURCE');
  $this->auth->assertCanAccessAdmin($target);$hash=hash('sha256',json_encode([$target,$amount,trim($notes)],JSON_THROW_ON_ERROR));$this->db->beginTransaction();
  try{
   $ids=[$source,$target];sort($ids);$accounts=[];foreach($ids as $id){$q=$this->db->prepare('SELECT a.id,a.parent_id,a.is_active,COALESCE(r.role_key,a.role) role FROM um_admins a JOIN um_admin_network_access n ON n.admin_id=a.id AND n.network_id=? AND n.is_active=1 AND (n.starts_at IS NULL OR n.starts_at<=NOW()) AND (n.expires_at IS NULL OR n.expires_at>NOW()) LEFT JOIN um_admin_network_roles r ON r.admin_id=a.id AND r.network_id=n.network_id AND r.is_active=1 WHERE a.id=? FOR UPDATE');$q->execute([$net,$id]);$accounts[$id]=$q->fetch(PDO::FETCH_ASSOC);if(!$accounts[$id]||!(int)$accounts[$id]['is_active'])throw new DomainException('FORBIDDEN_NETWORK');}
   if(!in_array($this->auth->role(),['system_owner','superadmin'],true)){$allowed=['admin'=>['distributor'],'distributor'=>['pos_agent','agent'],'agent'=>['pos_agent']];if((int)$accounts[$target]['parent_id']!==$source||!in_array($accounts[$target]['role'],$allowed[$this->auth->role()]??[],true))throw new DomainException('FORBIDDEN_SCOPE');}
   $q=$this->db->prepare('SELECT transfer_no,request_hash,amount,cost_value,status FROM um_instant_balance_transfers WHERE network_id=? AND sender_admin_id=? AND request_key=? FOR UPDATE');$q->execute([$net,$source,$key]);if($old=$q->fetch(PDO::FETCH_ASSOC)){if(!hash_equals((string)$old['request_hash'],$hash))throw new DomainException('IDEMPOTENCY_CONFLICT');if($old['status']!=='completed')throw new DomainException('TRANSFER_LOCKED');$this->db->commit();return ['success'=>true,'replayed'=>true,'transfer_no'=>$old['transfer_no'],'amount'=>$old['amount'],'cost_value'=>$old['cost_value']];}
   $left=$amount;$costTotal=0;$parts=[];$no='IBT-'.bin2hex(random_bytes(16));$nearest=null;
   foreach([false,true] as $permanent){if($left===0)break;$cap=500-count($parts);$condition=$permanent?'expires_at IS NULL':'expires_at>NOW()';$q=$this->db->prepare('SELECT id,remaining_amount,remaining_cost,expires_at FROM um_instant_balance_lots FORCE INDEX(idx_ib_lot_transfer) WHERE network_id=? AND owner_admin_id=? AND status=\'active\' AND remaining_amount>0 AND '.$condition.' ORDER BY expires_at,id LIMIT '.($cap+1).' FOR UPDATE');$q->execute([$net,$source]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);$more=count($rows)>$cap;if($more)array_pop($rows);
    foreach($rows as $lot){if($left===0)break;$available=$this->cents((string)$lot['remaining_amount']);$cost=$this->cents((string)$lot['remaining_cost']);$take=min($left,$available);if($take!==$available){$q=$this->db->prepare('SELECT ROUND(CAST(? AS DECIMAL(14,2))*CAST(? AS DECIMAL(14,2))/CAST(? AS DECIMAL(14,2)),2)');$q->execute([$this->money($cost),$this->money($take),$this->money($available)]);$cost=$this->cents((string)$q->fetchColumn());}
     $remaining=$available-$take;$remainingCost=$this->cents((string)$lot['remaining_cost'])-$cost;if($remainingCost<0)throw new DomainException('LOT_COST_INVALID');$q=$this->db->prepare('UPDATE um_instant_balance_lots SET remaining_amount=?,remaining_cost=?,status=? WHERE network_id=? AND id=?');$q->execute([$this->money($remaining),$this->money($remainingCost),$remaining===0?'depleted':'active',$net,$lot['id']]);
     $q=$this->db->prepare('INSERT INTO um_instant_balance_lots(network_id,owner_admin_id,source_lot_id,original_amount,original_cost,remaining_amount,remaining_cost,expires_at,granted_by_admin_id) VALUES(?,?,?,?,?,?,?,?,?)');$q->execute([$net,$target,$lot['id'],$this->money($take),$this->money($cost),$this->money($take),$this->money($cost),$lot['expires_at'],$source]);
     $q=$this->db->prepare("INSERT INTO um_instant_balance_consumptions(network_id,lot_id,owner_admin_id,event_type,reference_no,amount,cost_amount) VALUES(?,?,?,'transfer',?,?,?)");$q->execute([$net,$lot['id'],$source,$no,$this->money($take),$this->money($cost)]);$parts[]=(int)$lot['id'];$left-=$take;$costTotal+=$cost;if($lot['expires_at']!==null&&($nearest===null||$lot['expires_at']<$nearest))$nearest=$lot['expires_at'];
    }if($left>0&&$more)throw new DomainException('TRANSFER_BATCH_REQUIRED');
   }
   if($left>0)throw new DomainException('INSUFFICIENT_BALANCE');if($costTotal>99999999999999)throw new InvalidArgumentException('MONEY_RANGE');
   $q=$this->db->prepare('INSERT INTO um_instant_balance_transfers(network_id,transfer_no,sender_admin_id,receiver_admin_id,amount,cost_value,expires_at,notes,request_key,request_hash) VALUES(?,?,?,?,?,?,?,?,?,?)');$q->execute([$net,$no,$source,$target,$this->money($amount),$this->money($costTotal),$nearest,trim($notes),$key,$hash]);$this->auth->audit('instant_balance.transfer','allow','instant_balance_transfer',(int)$this->db->lastInsertId(),'preserve exact lot value cost and source expiry');$this->db->commit();return ['success'=>true,'transfer_no'=>$no,'amount'=>$this->money($amount),'cost_value'=>$this->money($costTotal),'expires_at'=>$nearest,'lots_count'=>count($parts)];
  }catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
}
