<?php
declare(strict_types=1);
/** Custody transfer; distribution debt and recorded acquisition cost are distinct. */
final class StockTransferApprovalService {
 public function __construct(private PDO $db,private AuthorizationContext $auth){}
 private function cents(string $v):int{if(!preg_match('/^(-?)(\d{1,12})(?:\.(\d{1,2}))?$/',$v,$m))throw new InvalidArgumentException('MONEY_RANGE');$n=(int)$m[2]*100+(int)str_pad($m[3]??'',2,'0');return $m[1]==='-'?-$n:$n;}
 private function money(int $v):string{return ($v<0?'-':'').intdiv(abs($v),100).'.'.str_pad((string)(abs($v)%100),2,'0',STR_PAD_LEFT);}
 private function transfer(int $id,bool $lock=false):array{
  $this->auth->assertCan(['warehouse_stock_transfer','card_warehouses']);$net=$this->auth->activeNetworkId();if($net<=0||!$this->auth->canAccessNetwork($net))throw new DomainException('FORBIDDEN_NETWORK');
  $q=$this->db->prepare('SELECT * FROM um_stock_transfers WHERE id=? AND network_id=?'.($lock?' FOR UPDATE':''));$q->execute([$id,$net]);$row=$q->fetch(PDO::FETCH_ASSOC);if(!$row)throw new DomainException('FORBIDDEN_NETWORK');
  $manager=in_array($this->auth->role(),['system_owner','superadmin','network_manager','admin'],true);if(!$manager&&(int)$row['receiver_admin_id']!==$this->auth->id())throw new DomainException('FORBIDDEN_SCOPE');
  if($manager){$this->auth->assertCanAccessAdmin((int)$row['sender_admin_id']);$this->auth->assertCanAccessAdmin((int)$row['receiver_admin_id']);}
  if((int)$row['sender_admin_id']===(int)$row['receiver_admin_id'])throw new InvalidArgumentException('SAME_WAREHOUSE');
  if(!in_array($row['transfer_type'],['transfer','return'],true))throw new DomainException('SALES_INVOICE_REQUIRED');return $row;
 }
 private function inspect(array $row,bool $lock=false):array{
  if(!in_array($row['status'],['draft','pending_approval'],true)||(int)$row['is_immutable']===1||!empty($row['journal_entry_id'])||!empty($row['financial_tx_id']))throw new DomainException('IMMUTABLE_RECORD');
  $raw=(string)$row['sheet_numbers'];if(strlen($raw)>6000||!preg_match('/^\d+(?:,\d+)*$/',$raw))throw new InvalidArgumentException('INVALID_SHEETS');$sheets=array_values(array_unique(array_map('intval',explode(',',$raw))));if(count($sheets)>500||min($sheets)<1)throw new DomainException('TRANSFER_BATCH_REQUIRED');
  $marks=implode(',',array_fill(0,count($sheets),'?'));$net=(int)$row['network_id'];$source=(int)$row['sender_admin_id'];
  foreach([$source,(int)$row['receiver_admin_id']] as $admin){$q=$this->db->prepare('SELECT a.id FROM um_admins a JOIN um_admin_network_access n ON n.admin_id=a.id AND n.network_id=? AND n.is_active=1 AND (n.starts_at IS NULL OR n.starts_at<=NOW()) AND (n.expires_at IS NULL OR n.expires_at>NOW()) WHERE a.id=? AND a.is_active=1');$q->execute([$net,$admin]);if(!$q->fetchColumn())throw new DomainException('FORBIDDEN_NETWORK');}
  $q=$this->db->prepare("SELECT m.id,m.username,m.sheet_no,m.profile_name,m.is_sold,m.invoice_id,m.first_login,m.status,m.comment,m.purchase_cost,m.price, p.cost_price distribution_price,COALESCE(p.retail_price,m.price) retail_price,EXISTS(SELECT 1 FROM radacct r WHERE r.network_id=m.network_id AND r.username=m.username) has_usage FROM um_vouchers_meta m LEFT JOIN um_profiles_def p ON p.network_id=m.network_id AND p.name=m.profile_name WHERE m.network_id=? AND m.owner_admin_id=? AND m.sheet_no IN ($marks) ORDER BY m.id LIMIT 5001".($lock?' FOR UPDATE':''));$q->execute(array_merge([$net,$source],$sheets));$cards=$q->fetchAll(PDO::FETCH_ASSOC);
  if(count($cards)>5000)throw new DomainException('TRANSFER_BATCH_REQUIRED');if(count($cards)!==(int)$row['cards_count']||count(array_unique(array_column($cards,'sheet_no')))!==count($sheets))throw new DomainException('TRANSFER_STALE');
  $value=0;$cost=0;$retail=0;foreach($cards as $card){if((int)$card['is_sold']||$card['invoice_id']!==null||$card['first_login']!==null||(int)$card['has_usage']||!in_array($card['status'],[null,'active','disabled'],true)||str_starts_with($card['username'],'router_')||str_starts_with((string)$card['comment'],'استيراد محجور من User Manager'))throw new DomainException('TRANSFER_STALE');if($card['distribution_price']===null)throw new DomainException('DISTRIBUTION_PRICE_REQUIRED');$value+=$this->cents((string)$card['distribution_price']);$cost+=$this->cents((string)$card['purchase_cost']);$retail+=$this->cents((string)$card['retail_price']);}
  if(min($value,$cost,$retail)<0||max($value,$cost,$retail)>999999999999)throw new InvalidArgumentException('MONEY_RANGE');return ['cards'=>$cards,'value'=>$value,'cost'=>$cost,'retail'=>$retail,'signature'=>hash('sha256',json_encode([$row['id'],$net,$source,$row['receiver_admin_id'],$cards],JSON_THROW_ON_ERROR))];
 }
 private function token(array $details,int $expires):string{return $expires.'.'.hash_hmac('sha256',$details['signature'].':'.$this->auth->id().':'.$expires,DB_PASS);}
 public function quote(int $id):array{$row=$this->transfer($id);$details=$this->inspect($row);$expires=time()+300;return ['success'=>true,'transfer_id'=>$id,'distribution_value'=>$this->money($details['value']),'purchase_cost'=>$this->money($details['cost']),'retail_value'=>$this->money($details['retail']),'previous_document_value'=>$row['total_value'],'cards_count'=>count($details['cards']),'quote_token'=>$this->token($details,$expires),'expires_at'=>$expires,'basis'=>'current_network_distribution_price'];}
 private function chart(int $net,string $code,string $name):int{$q=$this->db->prepare("INSERT INTO um_chart_of_accounts(network_id,account_code,name_ar,account_type,is_active,is_system,level) VALUES(?,?,?,'asset',1,1,4) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)");$q->execute([$net,$code,$name]);$q=$this->db->prepare('SELECT id FROM um_chart_of_accounts WHERE network_id=? AND account_code=? AND is_active=1 AND account_type=\'asset\' FOR UPDATE');$q->execute([$net,$code]);$id=(int)$q->fetchColumn();if(!$id)throw new DomainException('CHART_ACCOUNT_INVALID');return $id;}
 public function approve(int $id,array $input):array{
  if(isset($input['network_id'])&&(int)$input['network_id']!==$this->auth->activeNetworkId())throw new DomainException('FORBIDDEN_NETWORK');$this->db->beginTransaction();
  try{
   $row=$this->transfer($id,true);if($row['status']==='posted'){if((float)$row['cost_value']>0&&!$row['journal_entry_id'])throw new DomainException('POSTED_TRANSFER_INCOMPLETE');$this->db->commit();return ['success'=>true,'status'=>'posted','replayed'=>true,'transfer_no'=>$row['transfer_no']];}
   $details=$this->inspect($row,true);if(isset($input['quote_token'])&&!is_string($input['quote_token']))throw new InvalidArgumentException('INVALID_QUOTE');if(isset($input['expected_total_value'])&&!is_string($input['expected_total_value'])&&!is_int($input['expected_total_value']))throw new InvalidArgumentException('INVALID_QUOTE');$token=(string)($input['quote_token']??'');$parts=explode('.',$token,2);$expires=(int)($parts[0]??0);if($expires<time()||$expires>time()+300||!hash_equals($this->token($details,$expires),$token)||!isset($input['expected_total_value'])||$this->cents((string)$input['expected_total_value'])!==$details['value'])throw new DomainException('QUOTE_CHANGED');
   $net=(int)$row['network_id'];$source=(int)$row['sender_admin_id'];$target=(int)$row['receiver_admin_id'];$value=$details['value'];$balances=[];$ids=[$source,$target];sort($ids);
   foreach($ids as $admin){$q=$this->db->prepare('SELECT b.balance,b.credit_limit,a.role FROM um_admin_network_balances b JOIN um_admins a ON a.id=b.admin_id WHERE b.network_id=? AND b.admin_id=? FOR UPDATE');$q->execute([$net,$admin]);$balances[$admin]=$q->fetch(PDO::FETCH_ASSOC);if(!$balances[$admin])throw new DomainException('FORBIDDEN_NETWORK');}
   $targetCharged=!in_array($balances[$target]['role'],['system_owner','superadmin'],true);$sourceCredited=!in_array($balances[$source]['role'],['system_owner','superadmin'],true);
   if($targetCharged){$new=$this->cents((string)$balances[$target]['balance'])+$value;$limit=$this->cents((string)$balances[$target]['credit_limit']);if($limit>0&&$new>$limit)throw new DomainException('CREDIT_LIMIT_EXCEEDED');}
   $financialId=null;foreach([[$target,$targetCharged,1],[$source,$sourceCredited,-1]] as [$admin,$apply,$sign]){if(!$apply||$value===0)continue;$new=$this->cents((string)$balances[$admin]['balance'])+$sign*$value;if(abs($new)>999999999999)throw new InvalidArgumentException('MONEY_RANGE');$q=$this->db->prepare('UPDATE um_admin_network_balances SET balance=? WHERE network_id=? AND admin_id=?');$q->execute([$this->money($new),$net,$admin]);$q=$this->db->prepare("INSERT INTO um_financial_transactions(network_id,tx_no,account_id,tx_type,debit,credit,balance_after,cashbox_impact,payment_method,reference_id,description,created_by) VALUES(?,?,?,'transfer',?,?,?,0,'credit',?,?,?)");$q->execute([$net,'TX-'.bin2hex(random_bytes(16)),$admin,$sign>0?$this->money($value):'0.00',$sign<0?$this->money($value):'0.00',$this->money($new),$row['transfer_no'],'عهدة كروت بسعر التوزيع '.$row['transfer_no'],$this->auth->id()]);if($sign>0)$financialId=(int)$this->db->lastInsertId();}
   $journal=null;if($details['cost']>0){require_once __DIR__.'/FinancialAccountingService.php';$inventory=$this->chart($net,'110401','مخزون الكروت');$custody=$this->chart($net,'110301','مخزون الكروت في العهد');$return=$row['transfer_type']==='return';$amount=$this->money($details['cost']);$journal=(new FinancialAccountingService($this->db))->createJournalEntry(['source_module'=>'stock_movement','reference_no'=>$row['transfer_no'],'description'=>'نقل تكلفة شراء الكروت بين المخزون والعهد - '.$row['transfer_no'],'lines'=>[['account_id'=>$return?$inventory:$custody,'debit'=>$amount,'credit'=>0],['account_id'=>$return?$custody:$inventory,'debit'=>0,'credit'=>$amount]]],$this->auth->id())['entry_id'];if(!$journal)throw new RuntimeException('JOURNAL_REQUIRED');}
   foreach(array_chunk($details['cards'],250) as $chunk){$ids=array_column($chunk,'id');$marks=implode(',',array_fill(0,count($ids),'?'));$q=$this->db->prepare("UPDATE um_vouchers_meta SET owner_admin_id=? WHERE network_id=? AND owner_admin_id=? AND id IN ($marks)");$q->execute(array_merge([$target,$net,$source],$ids));if($q->rowCount()!==count($ids))throw new DomainException('TRANSFER_STALE');}
   $q=$this->db->prepare("UPDATE um_stock_transfers SET total_value=?,unit_price=?,cost_value=?,retail_value=?,status='posted',is_immutable=1,financial_tx_id=?,journal_entry_id=?,approved_by=?,approved_at=NOW() WHERE id=? AND network_id=?");$q->execute([$this->money($value),number_format($value/100/count($details['cards']),2,'.',''),$this->money($details['cost']),$this->money($details['retail']),$financialId,$journal,$this->auth->id(),$id,$net]);$this->auth->audit('stock.transfer.approve','allow','stock_transfer',$id,'quoted distribution debt; acquisition-cost custody journal');$this->db->commit();
   return ['success'=>true,'status'=>'posted','transfer_no'=>$row['transfer_no'],'total_value'=>$this->money($value),'cost_value'=>$this->money($details['cost']),'journal_entry_id'=>$journal,'message'=>'تم اعتماد العهدة بسعر التوزيع ونقل تكلفة شراء الكروت دون تكرار الأثر'];
  }catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
}
